code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    SP_VERSION: 0.85.6
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  image: "cirrusci/flutter:stable"
  script:
    - cd flutter_plugin_qpos/example
    - flutter build apk
  artifacts:
    paths:
      - flutter_plugin_qpos/example/build/app/outputs/flutter-apk/app-release.apk
