code_quality:
  stage: test
  image: "cirrusci/flutter:1.22.5"
  before_script:
    - pub global activate dart_code_metrics
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  allow_failure: true
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  # image: "cirrusci/flutter:1.22.5"
  # before_script:
  #   - pub global activate junitreport
  #   - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    # - cd flutter_demo/
    - cd flutter_plugin_qpos/example
    - flutter build apk
  #   - flutter test --machine --coverage | tojunit -o report.xml
  #   - lcov --summary coverage/lcov.info
  #   - genhtml coverage/lcov.info --output=coverage
  # coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    # name: coverage
    paths:
      - /build/app/outputs/flutter-apk/app-release.apk
    # reports:
    #   junit: report.xml