code_quality:
  stage: test
  image: "cirrusci/flutter:1.22.5"
  before_script:
    - pub global activate dart_code_metrics
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  image: "cirrusci/flutter:1.22.5"
  before_script:
    - pub global activate junitreport
  script:
    - cd flutter_demo/
    - flutter test --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - /build/app/outputs/apk/debug/app-debug.apk
    reports:
      junit: report.xml