name: Build Flutter APK

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get
        working-directory: flutter_plugin_qpos

      - name: Analyze (non-fatal)
        run: flutter analyze || true
        working-directory: flutter_plugin_qpos

      - name: Build APK
        run: flutter build apk --release
        working-directory: flutter_plugin_qpos/example


      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: flutter_plugin_qpos/example/build/app/outputs/flutter-apk/app-release.apk
